### ISSUE TITLE
Dependencies are not version pinned

### ISSUE THREAD

**Issue by lodu** [AlexAntonides/wscbs-as#1]
Have you considered what happens when a dependency has breaking changes when a newer version arrives?

To Fix: please version pin [`requirements.txt`'s](https://github.com/AlexAntonides/wscbs-as/blob/master/requirements.txt) requirements like so:
```
flask==1.0.0
validators==1.0.0
pytest==1.0.0
pyjwt==1.0.0
```
Please not that the example above uses version `1.0.0` which, most likely, won't be the actual version.

**Comment by AlexAntonides** [comment]
Opinion rejected.
